[package]
name = "aqiv"
version = "1.0.0"
edition = "2024"
authors = ["arabian"]
readme = "README.md"
keywords = ["image", "viewer", "png", "jpeg"]
description = "Quick Simple Image Viewer"

[dependencies]
egui = "0.31.1"
eframe = "0.31.1"
egui_extras = { version = "0.31.1", features = ["all_loaders"] }
egui-notify = "0.19.0"
image = { version = "0.25.6", features = ["default"] }
screen_size = "0.1"

[profile.release]
strip = true
lto = true
codegen-units = 1
opt-level = "z"
panic = "abort"


