[package]
name = "aqiv"
version = "1.0.3-1"
edition = "2024"
authors = ["arabian"]
readme = "README.md"
license = "MIT"
keywords = ["image", "viewer", "png", "jpeg"]
description = "arabian's Quick Image Viewer"
repository = "https://github.com/arabianq/aqiv"
homepage = "https://github.com/arabianq/aqiv"

[dependencies]
egui = { version = "0.31.1", features = ["default"]}
eframe = { version = "0.31.1", features = ["default"]}
egui_extras = { version = "0.31.1", features = ["image", "file", "svg"] }
egui-notify = { version = "0.19.0"}
image = { version = "0.25.6", features = ["png", "jpeg", "bmp", "tiff", "ico"] }
screen_size = { version = "0.1"}

[profile.release]
strip = true
lto = true
codegen-units = 1
opt-level = "z"
panic = "abort"


